"""empty message

Revision ID: 0336bea87c8b
Revises: 5b8c9eac4851
Create Date: 2017-01-29 08:13:05.338168

"""

# revision identifiers, used by Alembic.
revision = '0336bea87c8b'
down_revision = '5b8c9eac4851'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
