"""empty message

Revision ID: 31f6c4dfa8d0
Revises: bb7fd1e9f45c
Create Date: 2017-01-28 17:48:59.622977

"""

# revision identifiers, used by Alembic.
revision = '31f6c4dfa8d0'
down_revision = 'bb7fd1e9f45c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
