"""empty message

Revision ID: 5aa6c9cdf460
Revises: e9d9327161fe
Create Date: 2017-01-24 07:45:10.329909

"""

# revision identifiers, used by Alembic.
revision = '5aa6c9cdf460'
down_revision = 'e9d9327161fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'user_id')
    # ### end Alembic commands ###
