"""empty message

Revision ID: 5b8c9eac4851
Revises: 31f6c4dfa8d0
Create Date: 2017-01-29 06:58:00.962677

"""

# revision identifiers, used by Alembic.
revision = '5b8c9eac4851'
down_revision = '31f6c4dfa8d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
