"""empty message

Revision ID: bb7fd1e9f45c
Revises: 5aa6c9cdf460
Create Date: 2017-01-25 21:45:23.596041

"""

# revision identifiers, used by Alembic.
revision = 'bb7fd1e9f45c'
down_revision = '5aa6c9cdf460'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_heap', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sources', sa.Column('source_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'source_lists', ['source_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'source_list_id')
    op.drop_table('source_lists')
    # ### end Alembic commands ###
